# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Пицца')),
                ('descr', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
            },
        ),
        migrations.AlterModelOptions(
            name='pizzashop',
            options={'verbose_name': 'Пиццерия', 'verbose_name_plural': 'Пиццерии'},
        ),
        migrations.RenameField(
            model_name='pizzashop',
            old_name='desc',
            new_name='descr',
        ),
        migrations.AlterField(
            model_name='pizzashop',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Пиццерия'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizzashopKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreApp.PizzaShop'),
        ),
    ]
